//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnas.OGX2.Webparts.WP_ImportaSolicitacoes {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class WP_ImportaSolicitacoes {
        
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;
        
        protected global::System.Web.UI.WebControls.FileUpload flpArquivo;
        
        protected global::System.Web.UI.WebControls.Button btnUpload;
        
        protected global::System.Web.UI.WebControls.Literal erros;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divValidacao;
        
        public static implicit operator global::System.Web.UI.TemplateControl(WP_ImportaSolicitacoes target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Selected = true;
            @__ctrl.Text = "-- Selecione um Tipo --";
            @__ctrl.Value = "0";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control4() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "Plano de Melhoria - Mudanças";
            @__ctrl.Value = "1";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control5() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "Plano de Reforço - Mudanças";
            @__ctrl.Value = "2";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control6() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "Plano por Superação - Mudanças";
            @__ctrl.Value = "3";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control4();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control5();
            @__ctrl.Add(@__ctrl3);
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control6();
            @__ctrl.Add(@__ctrl4);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlTipo() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlTipo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlTipo";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            this.@__BuildControl__control2(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlflpArquivo() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            this.flpArquivo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "flpArquivo";
            @__ctrl.ViewStateMode = global::System.Web.UI.ViewStateMode.Enabled;
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnUpload() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnUpload = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Carregar para o Sistema";
            @__ctrl.CssClass = "btnUpload";
            @__ctrl.ID = "btnUpload";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Click -= new System.EventHandler(this.btnUpload_Click);
            @__ctrl.Click += new System.EventHandler(this.btnUpload_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlerros() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.erros = @__ctrl;
            @__ctrl.ID = "erros";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivValidacao() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divValidacao = @__ctrl;
            @__ctrl.ID = "divValidacao";
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControlerros();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Furnas.OGX2.Webparts.WP_ImportaSolicitacoes.WP_ImportaSolicitacoes @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../SiteAssets/CSS/importexcel.cs" +
                        "s\" />\r\n<script type=\"text/javascript\" src=\"../SiteAssets/JS/importSolicitacoes.j" +
                        "s\"></script>\r\n<style>\r\n    .modal{\r\n        position: fixed;\r\n        top: 0;\r\n " +
                        "       left: 0;\r\n        background-color: black;\r\n        z-index: 99;\r\n       " +
                        " opacity: 0.3;\r\n        filter: alpha(opacity=30);\r\n        -moz-opacity: 0.3;\r\n" +
                        "        min-height: 100%;\r\n        width: 100%;\r\n    }\r\n\r\n    .loading{\r\n       " +
                        " text-align: center;\r\n        font-family: Arial;\r\n        font-size: 10pt;\r\n   " +
                        "     border: 2px solid #67CFF5;\r\n        width: 200px;\r\n        height: 110px;\r\n" +
                        "        display: none;\r\n        position: fixed;\r\n        background-color: Whit" +
                        "e;\r\n        z-index: 999;\r\n        font-weight:bold;\r\n    }\r\n</style>\r\n\r\n<script" +
                        " type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/j" +
                        "query.min.js\"></script>\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    function ShowP" +
                        "rogress() {\r\n        setTimeout(function () {\r\n            var modal = $(\'<div /" +
                        ">\');\r\n            modal.addClass(\"modal\");\r\n            $(\'body\').append(modal);" +
                        "\r\n            var loading = $(\".loading\");\r\n            loading.show();\r\n       " +
                        "     var top = Math.max($(window).height() / 2 - loading[0].offsetHeight / 2, 0)" +
                        ";\r\n            var left = Math.max($(window).width() / 2 - loading[0].offsetWidt" +
                        "h / 2, 0);\r\n            loading.css({ top: top, left: left });\r\n        }, 200);" +
                        "\r\n    }\r\n\r\n</script>\r\n\r\n<header>\r\n    <h1 class=\"tituloPesquisa\">IMPORTAR SOLICI" +
                        "TAÇÕES DE PLANOS</h1>\r\n</header>\r\n<div id=\"spe-report-aporte\" class=\"ConteudoPag" +
                        "ina \">\r\n    <div class=\"propriedades\">\r\n        <div class=\"propriedadesTipo fil" +
                        "ter2\">\r\n            <h2 style=\"color:#262626;\">Tipo de Solicitação</h2>\r\n       " +
                        "     <br />\r\n            "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControlddlTipo();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n    </div>\r\n    <div class=\"tabelaDados\">\r\n        <div class=\"" +
                        "propriedadesfileInterfaceSPE\">\r\n            "));
            global::System.Web.UI.WebControls.FileUpload @__ctrl2;
            @__ctrl2 = this.@__BuildControlflpArquivo();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.Button @__ctrl3;
            @__ctrl3 = this.@__BuildControlbtnUpload();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n    </div>\r\n</div>\r\n"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl4;
            @__ctrl4 = this.@__BuildControldivValidacao();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<div id=\"containerModelos\" class=\"modelosN\">\r\n        <!-- Preenchido Via REST " +
                        "API -->\r\n</div>\r\n\r\n<div class=\"loading\">\r\n    <br />Carregando, por favor aguard" +
                        "e...<br /><br />\r\n    <img src=\"../SiteAssets/CSS/ajax-loader.gif\" alt=\"\" />\r\n</" +
                        "div>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
