//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnas.OGX2.Webparts.WP_PesquisaSGPMR {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class WP_PesquisaSGPMR {
        
        protected global::System.Web.UI.HtmlControls.HtmlSelect drpTipo;
        
        protected global::System.Web.UI.WebControls.DropDownList drpCiclo;
        
        protected global::System.Web.UI.WebControls.TextBox txtNumeracao;
        
        protected global::System.Web.UI.HtmlControls.HtmlSelect drpInstalacao;
        
        protected global::System.Web.UI.WebControls.TextBox txtOutraInstalacao;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divOutraInstalacao;
        
        protected global::System.Web.UI.WebControls.Label lblErroInstalacao;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divErroInstalacao;
        
        protected global::System.Web.UI.WebControls.DropDownList drpTipoEquipamento;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divTipoEquipamento;
        
        protected global::System.Web.UI.WebControls.TextBox txtCodIdentificacao;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCodIdentificacao;
        
        protected global::System.Web.UI.HtmlControls.HtmlSelect drpFuncaoTransmissao;
        
        protected global::System.Web.UI.WebControls.TextBox txtFuncaoTransmissao;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divOutraFuncaoTransmissao;
        
        protected global::System.Web.UI.WebControls.Label lblOutraFuncaoTransmissao;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divOutraFuncaoTransmissaoErro;
        
        protected global::System.Web.UI.WebControls.DropDownList drpRevitalizacao;
        
        protected global::System.Web.UI.WebControls.DropDownList drpIndicacoes;
        
        protected global::System.Web.UI.WebControls.TextBox dtInicio;
        
        protected global::System.Web.UI.WebControls.TextBox dtInicioFim;
        
        protected global::System.Web.UI.WebControls.Label ErroDt;
        
        protected global::System.Web.UI.WebControls.Label ErroDtFim;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ErrosDT;
        
        protected global::System.Web.UI.WebControls.DropDownList drpOrgaoSolicitante;
        
        protected global::System.Web.UI.WebControls.DropDownList drpOrgaoGestor;
        
        protected global::System.Web.UI.WebControls.DropDownList drpOrgaoGestorResponsavel;
        
        protected global::System.Web.UI.WebControls.Button btPesquisar;
        
        protected global::System.Web.UI.WebControls.Button btLimpar;
        
        protected global::System.Web.UI.WebControls.Button BtExportar;
        
        protected global::System.Web.UI.WebControls.GridView grid;
        
        protected global::System.Web.UI.WebControls.Label lblresultadoVazio;
        
        public static implicit operator global::System.Web.UI.TemplateControl(WP_PesquisaSGPMR target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control2() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "Planos de Melhorias e Reforços";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "1";
            @__ctrl.Text = "Plano de Reforços por Superação";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControldrpTipo() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.drpTipo = @__ctrl;
            @__ctrl.ID = "drpTipo";
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control2();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control3();
            @__parser.AddParsedSubObject(@__ctrl2);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control5() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Ciclo --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control4(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control5();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpCiclo() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpCiclo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpCiclo";
            this.@__BuildControl__control4(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtNumeracao() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtNumeracao = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtNumeracao";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control6() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione uma Instalação --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControldrpInstalacao() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.drpInstalacao = @__ctrl;
            @__ctrl.ID = "drpInstalacao";
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control6();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtOutraInstalacao() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtOutraInstalacao = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtOutraInstalacao";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivOutraInstalacao() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divOutraInstalacao = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fields");
            @__ctrl.ID = "divOutraInstalacao";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span class=\"labels\">&nbsp;&nbsp;</span>\r\n        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtOutraInstalacao();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span style=\"color:red;font-size: 10px;\">* Digite Outra Instalação</spa" +
                        "n>\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblErroInstalacao() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblErroInstalacao = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblErroInstalacao";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Text = "Insira o nome da Instalação.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivErroInstalacao() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divErroInstalacao = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fields");
            @__ctrl.ID = "divErroInstalacao";
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span class=\"labels\">&nbsp;&nbsp;</span>\r\n         "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllblErroInstalacao();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control8() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Tipo de Equipamento --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control7(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control8();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpTipoEquipamento() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpTipoEquipamento = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpTipoEquipamento";
            this.@__BuildControl__control7(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivTipoEquipamento() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divTipoEquipamento = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fields");
            @__ctrl.ID = "divTipoEquipamento";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span class=\"labels\">Tipo de Equipamento </span>\r\n        "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControldrpTipoEquipamento();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtCodIdentificacao() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtCodIdentificacao = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtCodIdentificacao";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivCodIdentificacao() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divCodIdentificacao = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fields");
            @__ctrl.ID = "divCodIdentificacao";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span class=\"labels\">Código de Identificação </span>\r\n        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtCodIdentificacao();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control9() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione uma Função de Transmissão --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControldrpFuncaoTransmissao() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.drpFuncaoTransmissao = @__ctrl;
            @__ctrl.ID = "drpFuncaoTransmissao";
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control9();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtFuncaoTransmissao() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtFuncaoTransmissao = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtFuncaoTransmissao";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivOutraFuncaoTransmissao() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divOutraFuncaoTransmissao = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fields");
            @__ctrl.ID = "divOutraFuncaoTransmissao";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span class=\"labels\">&nbsp;&nbsp;</span>\r\n        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtFuncaoTransmissao();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span style=\"color:red;font-size: 10px;\">* Digite Outra Função de Trans" +
                        "missão</span>\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblOutraFuncaoTransmissao() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblOutraFuncaoTransmissao = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblOutraFuncaoTransmissao";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Text = "Insira o nome da Função de Transmissão.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivOutraFuncaoTransmissaoErro() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divOutraFuncaoTransmissaoErro = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fields");
            @__ctrl.ID = "divOutraFuncaoTransmissaoErro";
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span class=\"labels\">&nbsp;&nbsp;</span>\r\n         "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllblOutraFuncaoTransmissao();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control11() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Status da Revitalização --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control12() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Não Iniciada";
            @__ctrl.Text = "Não Iniciada";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control13() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Em Andamento";
            @__ctrl.Text = "Em Andamento";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control14() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Executada";
            @__ctrl.Text = "Executada";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control10(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control11();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control12();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control13();
            @__ctrl.Add(@__ctrl3);
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control14();
            @__ctrl.Add(@__ctrl4);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpRevitalizacao() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpRevitalizacao = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpRevitalizacao";
            this.@__BuildControl__control10(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control16() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione uma Indicações --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control15(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control16();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpIndicacoes() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpIndicacoes = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpIndicacoes";
            this.@__BuildControl__control15(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControldtInicio() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.dtInicio = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dtInicio";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Month;
            @__ctrl.MaxLength = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControldtInicioFim() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.dtInicioFim = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dtInicioFim";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Month;
            @__ctrl.MaxLength = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlErroDt() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.ErroDt = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ErroDt";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Text = "As duas datas de Previsão da Instalação devem ser preenchidas.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlErroDtFim() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.ErroDtFim = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ErroDtFim";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Text = "A data final de Previsão da Instalação deve ser maior que a data inicial.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlErrosDT() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.ErrosDT = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fields");
            @__ctrl.ID = "ErrosDT";
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span class=\"labels\">&nbsp;&nbsp;</span>\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControlErroDt();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControlErroDtFim();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control18() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Órgão Solicitante --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control17(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control18();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpOrgaoSolicitante() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpOrgaoSolicitante = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpOrgaoSolicitante";
            this.@__BuildControl__control17(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control20() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Órgão Gestor --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control19(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control20();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpOrgaoGestor() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpOrgaoGestor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpOrgaoGestor";
            this.@__BuildControl__control19(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control22() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Responsável no Órgão Gestor --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control21(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control22();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpOrgaoGestorResponsavel() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpOrgaoGestorResponsavel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpOrgaoGestorResponsavel";
            this.@__BuildControl__control21(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtPesquisar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btPesquisar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btPesquisar";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Text = "Buscar";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(150D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.CssClass = "btDireita";
            @__ctrl.Click -= new System.EventHandler(this.btPesquisar_Click);
            @__ctrl.Click += new System.EventHandler(this.btPesquisar_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtLimpar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btLimpar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btLimpar";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Text = "Limpar Pesquisa";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(150D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.CssClass = "btEsquerda";
            @__ctrl.Click -= new System.EventHandler(this.btLimpar_Click);
            @__ctrl.Click += new System.EventHandler(this.btLimpar_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtExportar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.BtExportar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "BtExportar";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Text = "Exportar para o Excel";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(180D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.CssClass = "btExport";
            @__ctrl.Visible = false;
            @__ctrl.Click -= new System.EventHandler(this.BtExportar_Click);
            @__ctrl.Click += new System.EventHandler(this.BtExportar_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrid() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grid = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grid";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.CssClass = "cell-border stripe hover";
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblresultadoVazio() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblresultadoVazio = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblresultadoVazio";
            @__ctrl.Text = "Nenhum Plano encontrado.";
            @__ctrl.Visible = false;
            @__ctrl.CssClass = "resultVazio";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Furnas.OGX2.Webparts.WP_PesquisaSGPMR.WP_PesquisaSGPMR @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<style>\r\n    .modal{\r\n        position: fixed;\r\n        top: 0;\r\n        le" +
                        "ft: 0;\r\n        background-color: black;\r\n        z-index: 99;\r\n        opacity:" +
                        " 0.3;\r\n        filter: alpha(opacity=30);\r\n        -moz-opacity: 0.3;\r\n        m" +
                        "in-height: 100%;\r\n        width: 100%;\r\n    }\r\n\r\n    .loading{\r\n        text-ali" +
                        "gn: center;\r\n        font-family: Arial;\r\n        font-size: 10pt;\r\n        bord" +
                        "er: 2px solid #67CFF5;\r\n        width: 200px;\r\n        height: 110px;\r\n        d" +
                        "isplay: none;\r\n        position: fixed;\r\n        background-color: White;\r\n     " +
                        "   z-index: 999;\r\n        font-weight:bold;\r\n    }\r\n    .ms-webpartPage-root {\r\n" +
                        "        border-spacing: 0px!important;\r\n        margin-top: 20px!important;\r\n   " +
                        " }\r\n    .custom-combobox {\r\n    position: relative;\r\n    display: inline-block;\r" +
                        "\n  }\r\n  .custom-combobox-toggle {\r\n    position: absolute;\r\n    top: 0;\r\n    bot" +
                        "tom: 0;\r\n    margin-left: -1px;\r\n    padding: 0;\r\n  }\r\n  .custom-combobox-input " +
                        "{\r\n    margin: 0;\r\n    padding: 5px 10px;\r\n  }\r\n  span#DeltaPlaceHolderPageTitle" +
                        "InTitleArea {\r\n    display: none;\r\n}\r\n.labels {\r\n    width:230px;\r\n    float:lef" +
                        "t;\r\n}\r\n.pesq {\r\n    background-color: #f1f1f1;\r\n    padding:10px;\r\n    font-fami" +
                        "ly: \"Segoe UI Light\",\"Segoe UI\",\"Segoe\",Tahoma,Helvetica,Arial,sans-serif;\r\n    " +
                        "color: #262626;\r\n    font-size:14px;\r\n    border-radius: 10px;\r\n    border: 1px " +
                        "solid #ababab;\r\n}\r\n.tituloPesquisa {\r\n    font-family: \"Segoe UI Light\",\"Segoe U" +
                        "I\",\"Segoe\",Tahoma,Helvetica,Arial,sans-serif;\r\n    font-size: 25px;\r\n    margin-" +
                        "bottom: 10px;\r\n    font-weight:bold;\r\n}\r\n.fields {\r\n    padding-bottom:8px;\r\n}\r\n" +
                        ".btDireita {\r\n    margin-left: 0px!important;\r\n    background: url(../SiteAssets" +
                        "/magnifier.png) left 40px top 8px no-repeat;\r\n    cursor: pointer;\r\n    border-r" +
                        "adius: 5px;\r\n    font-size: 13px!important;\r\n    border: 1px solid #666!importan" +
                        "t;\r\n    padding-left: 25px!important;\r\n}\r\n.btEsquerda {\r\n    margin-left: 0px!im" +
                        "portant;\r\n    background: url(../SiteAssets/cross.png) left 20px top 9px no-repe" +
                        "at;\r\n    cursor: pointer;\r\n    font-size: 13px!important;\r\n    text-align: right" +
                        ";\r\n    padding-right: 15px!important;\r\n    border-radius: 5px;\r\n    border: 1px " +
                        "solid #666!important;\r\n}\r\n.btExport {\r\n    margin-left: 0px!important;\r\n    back" +
                        "ground: url(../SiteAssets/excel.png) left 20px top 9px no-repeat;\r\n    cursor: p" +
                        "ointer;\r\n    font-size: 13px!important;\r\n    text-align: right;\r\n    padding-rig" +
                        "ht: 15px!important;\r\n    border-radius: 5px;\r\n    border: 1px solid #666!importa" +
                        "nt;\r\n}\r\n.resultVazio {\r\n    font-size:17px; \r\n    color:#262626;\r\n    font-famil" +
                        "y: \"Segoe UI Light\",\"Segoe UI\",\"Segoe\",Tahoma,Helvetica,Arial,sans-serif;\r\n    f" +
                        "ont-weight:bold;\r\n}\r\n.tbCentro {\r\n    text-align: center;\r\n}\r\nselect {\r\n    min-" +
                        "width: 415px;\r\n}\r\n</style>\r\n\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../Si" +
                        "teAssets/JSManual/jquery-ui.theme.min.css\" />\r\n<link rel=\"stylesheet\" type=\"text" +
                        "/css\" href=\"../SiteAssets/JSManual/jquery-ui.theme.css\" />\r\n<link rel=\"styleshee" +
                        "t\" type=\"text/css\" href=\"../SiteAssets/JSManual/jquery-ui.structure.min.css\" />\r" +
                        "\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../SiteAssets/JSManual/jquery-ui.s" +
                        "tructure.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../SiteAssets/JSM" +
                        "anual/jquery-ui.min.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../Sit" +
                        "eAssets/JSManual/jquery-ui.css\" />\r\n\r\n\r\n\r\n<link rel=\"stylesheet\" type=\"text/css\"" +
                        " href=\"../SiteAssets/JSManual/jquery.dataTables.min.css\" />\r\n<script type=\"text/" +
                        "javascript\" src=\"https://cdn.datatables.net/v/dt/dt-1.10.22/datatables.min.js\"><" +
                        "/script>\r\n\r\n<script type=\"text/javascript\" src=\"../SiteAssets/JS/tabelaR.js\"></s" +
                        "cript>\r\n<script>\r\n\r\n\r\n    function ShowProgress() {\r\n        setTimeout(function" +
                        " () {\r\n            var modal = $(\'<div />\');\r\n            modal.addClass(\"modal\"" +
                        ");\r\n            $(\'body\').append(modal);\r\n            var loading = $(\".loading\"" +
                        ");\r\n            loading.show();\r\n            var top = Math.max($(window).height" +
                        "() / 2 - loading[0].offsetHeight / 2, 0);\r\n            var left = Math.max($(win" +
                        "dow).width() / 2 - loading[0].offsetWidth / 2, 0);\r\n            loading.css({ to" +
                        "p: top, left: left });\r\n        }, 200);\r\n    }\r\n\r\n    $(document).ready(functio" +
                        "n () {\r\n        $(\"#btPesquisar\").click(function () {\r\n            ShowProgress(" +
                        ");\r\n        });\r\n\r\n        $(\"#btLimpar\").click(function () {\r\n            ShowP" +
                        "rogress();\r\n        });\r\n\r\n        $(\"#BtExportar\").click(function () {\r\n       " +
                        "     ShowProgress();\r\n        });\r\n    });\r\n</script>\r\n\r\n<div><h2 class=\"tituloP" +
                        "esquisa\">Pesquisar Planos SGPMR</h2></div>\r\n<div class=\"pesq\">\r\n    <div class=\"" +
                        "fields\">\r\n        <span class=\"labels\">Tipo de Conteúdo </span>\r\n        "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl1;
            @__ctrl1 = this.@__BuildControldrpTipo();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Ciclo </span" +
                        ">\r\n        "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            @__ctrl2 = this.@__BuildControldrpCiclo();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Numeração </" +
                        "span>\r\n        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControltxtNumeracao();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Instalação <" +
                        "/span>\r\n        "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl4;
            @__ctrl4 = this.@__BuildControldrpInstalacao();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl5;
            @__ctrl5 = this.@__BuildControldivOutraInstalacao();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl6;
            @__ctrl6 = this.@__BuildControldivErroInstalacao();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl7;
            @__ctrl7 = this.@__BuildControldivTipoEquipamento();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl8;
            @__ctrl8 = this.@__BuildControldivCodIdentificacao();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Função de Transmissão </" +
                        "span>\r\n        "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl9;
            @__ctrl9 = this.@__BuildControldrpFuncaoTransmissao();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl10;
            @__ctrl10 = this.@__BuildControldivOutraFuncaoTransmissao();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl11;
            @__ctrl11 = this.@__BuildControldivOutraFuncaoTransmissaoErro();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Status da Revitalização " +
                        "</span>\r\n        "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl12;
            @__ctrl12 = this.@__BuildControldrpRevitalizacao();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Indicações" +
                        " </span>\r\n        "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl13;
            @__ctrl13 = this.@__BuildControldrpIndicacoes();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Previsão d" +
                        "a Instalação </span>\r\n        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            @__ctrl14 = this.@__BuildControldtInicio();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        &nbsp;até&nbsp;\r\n        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl15;
            @__ctrl15 = this.@__BuildControldtInicioFim();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl16;
            @__ctrl16 = this.@__BuildControlErrosDT();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Órgão Solicitante </sp" +
                        "an>\r\n        "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl17;
            @__ctrl17 = this.@__BuildControldrpOrgaoSolicitante();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Órgão Gest" +
                        "or </span>\r\n        "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl18;
            @__ctrl18 = this.@__BuildControldrpOrgaoGestor();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Responsáve" +
                        "l no Órgão Gestor </span>\r\n        "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl19;
            @__ctrl19 = this.@__BuildControldrpOrgaoGestorResponsavel();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n\r\n    <div style=\"margin-top:5px;padding-left:230px\">\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl20;
            @__ctrl20 = this.@__BuildControlbtPesquisar();
            @__parser.AddParsedSubObject(@__ctrl20);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        &nbsp;&nbsp;\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl21;
            @__ctrl21 = this.@__BuildControlbtLimpar();
            @__parser.AddParsedSubObject(@__ctrl21);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n</div>\r\n<div style=\"margin-top:10px\">\r\n    <div style=\"height:40px;" +
                        "float:right;\">\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl22;
            @__ctrl22 = this.@__BuildControlBtExportar();
            @__parser.AddParsedSubObject(@__ctrl22);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    "));
            global::System.Web.UI.WebControls.GridView @__ctrl23;
            @__ctrl23 = this.@__BuildControlgrid();
            @__parser.AddParsedSubObject(@__ctrl23);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            global::System.Web.UI.WebControls.Label @__ctrl24;
            @__ctrl24 = this.@__BuildControllblresultadoVazio();
            @__parser.AddParsedSubObject(@__ctrl24);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</div>\r\n\r\n<div class=\"loading\">\r\n    <br />Carregando, por favor aguarde...<br " +
                        "/><br />\r\n    <img src=\"../SiteAssets/CSS/ajax-loader.gif\" alt=\"\" />\r\n</div>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
