//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnas.OGX2.MTC.WebPartsPaginas.WP_Pesquisa {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class WP_Pesquisa {
        
        protected global::System.Web.UI.WebControls.DropDownList drpTipo;
        
        protected global::System.Web.UI.WebControls.DropDownList drpGrupo;
        
        protected global::System.Web.UI.WebControls.DropDownList drpSubgrupo;
        
        protected global::System.Web.UI.WebControls.DropDownList drpFabricante;
        
        protected global::System.Web.UI.WebControls.DropDownList drpOrgao;
        
        protected global::System.Web.UI.WebControls.TextBox dtInicio;
        
        protected global::System.Web.UI.WebControls.TextBox dtInicioFim;
        
        protected global::System.Web.UI.WebControls.Label ErroDt;
        
        protected global::System.Web.UI.WebControls.Label ErroDtFim;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ErrosDT;
        
        protected global::System.Web.UI.WebControls.TextBox dtFim;
        
        protected global::System.Web.UI.WebControls.TextBox dtFimFim;
        
        protected global::System.Web.UI.WebControls.Label ErroDt2;
        
        protected global::System.Web.UI.WebControls.Label ErroDtFim2;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ErrosDT2;
        
        protected global::System.Web.UI.WebControls.DropDownList dprControle;
        
        protected global::System.Web.UI.HtmlControls.HtmlSelect combobox;
        
        protected global::System.Web.UI.WebControls.TextBox txtlivre;
        
        protected global::System.Web.UI.WebControls.Button btPesquisar;
        
        protected global::System.Web.UI.WebControls.Button btLimpar;
        
        protected global::System.Web.UI.WebControls.GridView gridTeste;
        
        protected global::System.Web.UI.WebControls.Label lblresultadoVazio;
        
        protected global::System.Web.UI.WebControls.GridView GridView1;
        
        public static implicit operator global::System.Web.UI.TemplateControl(WP_Pesquisa target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Tipo --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpTipo() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpTipo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpTipo";
            this.@__BuildControl__control2(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control5() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Grupo --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control4(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control5();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpGrupo() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpGrupo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpGrupo";
            @__ctrl.AutoPostBack = true;
            this.@__BuildControl__control4(@__ctrl.Items);
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.drpGrupo_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.drpGrupo_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control7() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Subgrupo --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control6(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control7();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpSubgrupo() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpSubgrupo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpSubgrupo";
            this.@__BuildControl__control6(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control9() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Fabricante --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control8(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control9();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpFabricante() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpFabricante = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpFabricante";
            this.@__BuildControl__control8(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control11() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Órgão Resposável --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control10(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control11();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpOrgao() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpOrgao = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpOrgao";
            this.@__BuildControl__control10(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControldtInicio() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.dtInicio = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dtInicio";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Date;
            @__ctrl.MaxLength = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControldtInicioFim() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.dtInicioFim = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dtInicioFim";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Date;
            @__ctrl.MaxLength = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlErroDt() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.ErroDt = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ErroDt";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Text = "As datas de - até de Inicio de Vigência devem ser preenchidas.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlErroDtFim() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.ErroDtFim = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ErroDtFim";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Text = "A data final de Inicio de Vigência deve ser maior que a data inicial.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlErrosDT() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.ErrosDT = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fields");
            @__ctrl.ID = "ErrosDT";
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span class=\"labels\">&nbsp;&nbsp;</span>\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControlErroDt();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControlErroDtFim();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControldtFim() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.dtFim = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dtFim";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Date;
            @__ctrl.MaxLength = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControldtFimFim() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.dtFimFim = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dtFimFim";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Date;
            @__ctrl.MaxLength = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlErroDt2() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.ErroDt2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ErroDt2";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Text = "As datas De - até de Fim de Vigência devem ser preenchidas.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlErroDtFim2() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.ErroDtFim2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ErroDtFim2";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Text = "A data final de Fim de Vigência deve ser maior que a data inicial.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlErrosDT2() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.ErrosDT2 = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fields");
            @__ctrl.ID = "ErrosDT2";
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span class=\"labels\">&nbsp;&nbsp;</span>\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControlErroDt2();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControlErroDtFim2();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control13() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Status --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control14() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Aguardando Aprovação";
            @__ctrl.Text = "Aguardando Aprovação";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control15() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Vigente";
            @__ctrl.Text = "Vigente";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control16() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Para comentários";
            @__ctrl.Text = "Para comentários";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control17() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Em consolidação";
            @__ctrl.Text = "Em consolidação";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control18() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Histórico";
            @__ctrl.Text = "Histórico";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control19() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Cancelado";
            @__ctrl.Text = "Cancelado";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control12(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control13();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control14();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control15();
            @__ctrl.Add(@__ctrl3);
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control16();
            @__ctrl.Add(@__ctrl4);
            global::System.Web.UI.WebControls.ListItem @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control17();
            @__ctrl.Add(@__ctrl5);
            global::System.Web.UI.WebControls.ListItem @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control18();
            @__ctrl.Add(@__ctrl6);
            global::System.Web.UI.WebControls.ListItem @__ctrl7;
            @__ctrl7 = this.@__BuildControl__control19();
            @__ctrl.Add(@__ctrl7);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldprControle() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.dprControle = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dprControle";
            this.@__BuildControl__control12(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control20() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlcombobox() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.combobox = @__ctrl;
            @__ctrl.ID = "combobox";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control20();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtlivre() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtlivre = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtlivre";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtPesquisar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btPesquisar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btPesquisar";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Text = "Buscar";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(150D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.CssClass = "btDireita";
            @__ctrl.Click -= new System.EventHandler(this.btPesquisar_Click);
            @__ctrl.Click += new System.EventHandler(this.btPesquisar_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtLimpar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btLimpar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btLimpar";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Text = "Limpar Pesquisa";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(150D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.CssClass = "btEsquerda";
            @__ctrl.Click -= new System.EventHandler(this.btLimpar_Click);
            @__ctrl.Click += new System.EventHandler(this.btLimpar_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgridTeste() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.gridTeste = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "gridTeste";
            @__ctrl.CssClass = "cell-border stripe hover";
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblresultadoVazio() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblresultadoVazio = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblresultadoVazio";
            @__ctrl.Text = "Nenhum MTC encontrado.";
            @__ctrl.Visible = false;
            @__ctrl.CssClass = "resultVazio";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control21(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = global::System.Drawing.Color.White;
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(40, 71, 117)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control25() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "detalhes";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Ver detalhes"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control24(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.HyperLink @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control25();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control23() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control24), null);
            @__ctrl.HeaderText = "Ver detalhes";
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(120D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.ItemStyle.Width = new System.Web.UI.WebControls.Unit(120D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control26() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.HeaderText = "ID";
            @__ctrl.DataField = "ID";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control27() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.HeaderText = "Código MTC";
            @__ctrl.DataField = "CodigoMTC";
            @__ctrl.ItemStyle.Width = new System.Web.UI.WebControls.Unit(150D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control28() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.HeaderText = "Tipo MTC";
            @__ctrl.DataField = "TipoMTC";
            @__ctrl.ItemStyle.Width = new System.Web.UI.WebControls.Unit(80D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control29() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.HeaderText = "Grupo";
            @__ctrl.DataField = "Grupo";
            @__ctrl.ItemStyle.Width = new System.Web.UI.WebControls.Unit(120D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control30() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.HeaderText = "Subgrupo";
            @__ctrl.DataField = "Subgrupo";
            @__ctrl.ItemStyle.Width = new System.Web.UI.WebControls.Unit(120D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control31() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.HeaderText = "Fabricante";
            @__ctrl.DataField = "Fabricante1";
            @__ctrl.ItemStyle.Width = new System.Web.UI.WebControls.Unit(80D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control32() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.HeaderText = "Revisão";
            @__ctrl.DataField = "Revisao";
            @__ctrl.ItemStyle.Width = new System.Web.UI.WebControls.Unit(60D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control33() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.HeaderText = "Controle de Status";
            @__ctrl.DataField = "ControleStatus";
            @__ctrl.ItemStyle.Width = new System.Web.UI.WebControls.Unit(120D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control22(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.TemplateField @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control23();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control26();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control27();
            @__ctrl.Add(@__ctrl3);
            global::System.Web.UI.WebControls.BoundField @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control28();
            @__ctrl.Add(@__ctrl4);
            global::System.Web.UI.WebControls.BoundField @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control29();
            @__ctrl.Add(@__ctrl5);
            global::System.Web.UI.WebControls.BoundField @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control30();
            @__ctrl.Add(@__ctrl6);
            global::System.Web.UI.WebControls.BoundField @__ctrl7;
            @__ctrl7 = this.@__BuildControl__control31();
            @__ctrl.Add(@__ctrl7);
            global::System.Web.UI.WebControls.BoundField @__ctrl8;
            @__ctrl8 = this.@__BuildControl__control32();
            @__ctrl.Add(@__ctrl8);
            global::System.Web.UI.WebControls.BoundField @__ctrl9;
            @__ctrl9 = this.@__BuildControl__control33();
            @__ctrl.Add(@__ctrl9);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control34(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(153, 153, 153)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control35(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(93, 123, 157)));
            @__ctrl.Font.Bold = true;
            @__ctrl.ForeColor = global::System.Drawing.Color.White;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control36(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.Font.Size = new System.Web.UI.WebControls.FontUnit(new System.Web.UI.WebControls.Unit(1D, global::System.Web.UI.WebControls.UnitType.Em));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control37(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(40, 71, 117)));
            @__ctrl.ForeColor = global::System.Drawing.Color.White;
            @__ctrl.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control38(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(247, 246, 243)));
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(51, 51, 51)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control39(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(226, 222, 214)));
            @__ctrl.Font.Bold = true;
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(51, 51, 51)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control40(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(233, 231, 226)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control41(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(80, 108, 140)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control42(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(255, 253, 248)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control43(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(111, 141, 174)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.GridView @__BuildControlGridView1() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.GridView1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "GridView1";
            @__ctrl.CellPadding = 4;
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(51, 51, 51)));
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.None;
            @__ctrl.AutoGenerateColumns = false;
            this.@__BuildControl__control21(@__ctrl.AlternatingRowStyle);
            this.@__BuildControl__control22(@__ctrl.Columns);
            this.@__BuildControl__control34(@__ctrl.EditRowStyle);
            this.@__BuildControl__control35(@__ctrl.FooterStyle);
            this.@__BuildControl__control36(@__ctrl.HeaderStyle);
            this.@__BuildControl__control37(@__ctrl.PagerStyle);
            this.@__BuildControl__control38(@__ctrl.RowStyle);
            this.@__BuildControl__control39(@__ctrl.SelectedRowStyle);
            this.@__BuildControl__control40(@__ctrl.SortedAscendingCellStyle);
            this.@__BuildControl__control41(@__ctrl.SortedAscendingHeaderStyle);
            this.@__BuildControl__control42(@__ctrl.SortedDescendingCellStyle);
            this.@__BuildControl__control43(@__ctrl.SortedDescendingHeaderStyle);
            @__ctrl.RowDataBound -= new System.Web.UI.WebControls.GridViewRowEventHandler(this.GridView1_RowDataBound);
            @__ctrl.RowDataBound += new System.Web.UI.WebControls.GridViewRowEventHandler(this.GridView1_RowDataBound);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Furnas.OGX2.MTC.WebPartsPaginas.WP_Pesquisa.WP_Pesquisa @__ctrl) {
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControldrpTipo();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            @__ctrl2 = this.@__BuildControldrpGrupo();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            @__ctrl3 = this.@__BuildControldrpSubgrupo();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.DropDownList @__ctrl4;
            @__ctrl4 = this.@__BuildControldrpFabricante();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.WebControls.DropDownList @__ctrl5;
            @__ctrl5 = this.@__BuildControldrpOrgao();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControldtInicio();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            @__ctrl7 = this.@__BuildControldtInicioFim();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl8;
            @__ctrl8 = this.@__BuildControlErrosDT();
            @__parser.AddParsedSubObject(@__ctrl8);
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            @__ctrl9 = this.@__BuildControldtFim();
            @__parser.AddParsedSubObject(@__ctrl9);
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            @__ctrl10 = this.@__BuildControldtFimFim();
            @__parser.AddParsedSubObject(@__ctrl10);
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl11;
            @__ctrl11 = this.@__BuildControlErrosDT2();
            @__parser.AddParsedSubObject(@__ctrl11);
            global::System.Web.UI.WebControls.DropDownList @__ctrl12;
            @__ctrl12 = this.@__BuildControldprControle();
            @__parser.AddParsedSubObject(@__ctrl12);
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl13;
            @__ctrl13 = this.@__BuildControlcombobox();
            @__parser.AddParsedSubObject(@__ctrl13);
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            @__ctrl14 = this.@__BuildControltxtlivre();
            @__parser.AddParsedSubObject(@__ctrl14);
            global::System.Web.UI.WebControls.Button @__ctrl15;
            @__ctrl15 = this.@__BuildControlbtPesquisar();
            @__parser.AddParsedSubObject(@__ctrl15);
            global::System.Web.UI.WebControls.Button @__ctrl16;
            @__ctrl16 = this.@__BuildControlbtLimpar();
            @__parser.AddParsedSubObject(@__ctrl16);
            global::System.Web.UI.WebControls.GridView @__ctrl17;
            @__ctrl17 = this.@__BuildControlgridTeste();
            @__parser.AddParsedSubObject(@__ctrl17);
            global::System.Web.UI.WebControls.Label @__ctrl18;
            @__ctrl18 = this.@__BuildControllblresultadoVazio();
            @__parser.AddParsedSubObject(@__ctrl18);
            global::System.Web.UI.WebControls.GridView @__ctrl19;
            @__ctrl19 = this.@__BuildControlGridView1();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n<style>\r\n    .modal{\r\n        position: fixed;\r\n        top: 0;\r\n        left" +
                    ": 0;\r\n        background-color: black;\r\n        z-index: 99;\r\n        opacity: 0" +
                    ".3;\r\n        filter: alpha(opacity=30);\r\n        -moz-opacity: 0.3;\r\n        min" +
                    "-height: 100%;\r\n        width: 100%;\r\n    }\r\n\r\n    .loading{\r\n        text-align" +
                    ": center;\r\n        font-family: Arial;\r\n        font-size: 10pt;\r\n        border" +
                    ": 2px solid #67CFF5;\r\n        width: 200px;\r\n        height: 110px;\r\n        dis" +
                    "play: none;\r\n        position: fixed;\r\n        background-color: White;\r\n       " +
                    " z-index: 999;\r\n        font-weight:bold;\r\n    }\r\n    .ms-webpartPage-root {\r\n  " +
                    "      border-spacing: 0px!important;\r\n        margin-top: 20px!important;\r\n    }" +
                    "\r\n    .custom-combobox {\r\n    position: relative;\r\n    display: inline-block;\r\n " +
                    " }\r\n  .custom-combobox-toggle {\r\n    position: absolute;\r\n    top: 0;\r\n    botto" +
                    "m: 0;\r\n    margin-left: -1px;\r\n    padding: 0;\r\n  }\r\n  .custom-combobox-input {\r" +
                    "\n    margin: 0;\r\n    padding: 5px 10px;\r\n  }\r\n  span#DeltaPlaceHolderPageTitleIn" +
                    "TitleArea {\r\n    display: none;\r\n}\r\n.labels {\r\n    width:200px;\r\n    float:left;" +
                    "\r\n}\r\n.pesq {\r\n    background-color: #f1f1f1;\r\n    padding:10px;\r\n    font-family" +
                    ": \"Segoe UI Light\",\"Segoe UI\",\"Segoe\",Tahoma,Helvetica,Arial,sans-serif;\r\n    co" +
                    "lor: #262626;\r\n    font-size:14px;\r\n    border-radius: 10px;\r\n    border: 1px so" +
                    "lid #ababab;\r\n}\r\n.tituloPesquisa {\r\n    font-family: \"Segoe UI Light\",\"Segoe UI\"" +
                    ",\"Segoe\",Tahoma,Helvetica,Arial,sans-serif;\r\n    font-size: 25px;\r\n    margin-bo" +
                    "ttom: 10px;\r\n    font-weight:bold;\r\n}\r\n.fields {\r\n    padding-bottom:8px;\r\n}\r\n.b" +
                    "tDireita {\r\n    margin-left: 0px!important;\r\n    background: url(../SiteAssets/m" +
                    "agnifier.png) left 40px top 8px no-repeat;\r\n    cursor: pointer;\r\n    border-rad" +
                    "ius: 5px;\r\n    font-size: 13px!important;\r\n    border: 1px solid #666!important;" +
                    "\r\n    padding-left: 25px!important;\r\n}\r\n.btEsquerda {\r\n    margin-left: 0px!impo" +
                    "rtant;\r\n    background: url(../SiteAssets/cross.png) left 20px top 9px no-repeat" +
                    ";\r\n    cursor: pointer;\r\n    font-size: 13px!important;\r\n    text-align: right;\r" +
                    "\n    padding-right: 15px!important;\r\n    border-radius: 5px;\r\n    border: 1px so" +
                    "lid #666!important;\r\n}\r\n.resultVazio {\r\n    font-size:17px; \r\n    color:#262626;" +
                    "\r\n    font-family: \"Segoe UI Light\",\"Segoe UI\",\"Segoe\",Tahoma,Helvetica,Arial,sa" +
                    "ns-serif;\r\n    font-weight:bold;\r\n}\r\n.tbCentro {\r\n    text-align: center;\r\n}\r\n</" +
                    "style>\r\n\r\n\r\n\r\n<script src=\"../SiteAssets/JSManual/jquery-1.12.4.js\"></script>\r\n<" +
                    "script src=\"../SiteAssets/JSManual/jquery-ui.js\"></script>\r\n<script type=\"text/j" +
                    "avascript\" src=\"../SiteAssets/JSManual/CC.js\"></script>\r\n\r\n<link rel=\"stylesheet" +
                    "\" type=\"text/css\" href=\"../SiteAssets/JSManual/jquery-ui.theme.min.css\" />\r\n<lin" +
                    "k rel=\"stylesheet\" type=\"text/css\" href=\"../SiteAssets/JSManual/jquery-ui.theme." +
                    "css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../SiteAssets/JSManual/jqu" +
                    "ery-ui.structure.min.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../Si" +
                    "teAssets/JSManual/jquery-ui.structure.css\" />\r\n<link rel=\"stylesheet\" type=\"text" +
                    "/css\" href=\"../SiteAssets/JSManual/jquery-ui.min.css\" />\r\n<link rel=\"stylesheet\"" +
                    " type=\"text/css\" href=\"../SiteAssets/JSManual/jquery-ui.css\" />\r\n\r\n\r\n\r\n<link rel" +
                    "=\"stylesheet\" type=\"text/css\" href=\"../SiteAssets/JSManual/jquery.dataTables.min" +
                    ".css\" />\r\n<script type=\"text/javascript\" src=\"https://cdn.datatables.net/v/dt/dt" +
                    "-1.10.22/datatables.min.js\"></script>\r\n\r\n\r\n\r\n\r\n<script>\r\n    $(function () {\r\n  " +
                    "      $(\'#");
    @__w.Write(gridTeste.ClientID );

            @__w.Write("\').DataTable({\r\n            \"language\": {\r\n                \"url\": \"//cdn.datatabl" +
                    "es.net/plug-ins/1.10.22/i18n/Portuguese-Brasil.json\"\r\n            },\r\n          " +
                    "  \"searching\": false,\r\n            \"lengthChange\": false,\r\n            \"pageLeng" +
                    "th\": 50,\r\n            columnDefs: [\r\n                {\r\n                    targ" +
                    "ets: 0,\r\n                    \"className\": \"tbCentro\",\r\n                    rende" +
                    "r: function (data) {\r\n                        if(data !=\"-\" && data != \"&nbsp;\")" +
                    "\r\n                            return \'<img src=\"\' + data + \'\">\'\r\n               " +
                    "         else\r\n                            return \"\"\r\n                    }\r\n   " +
                    "             },\r\n                {\r\n                    targets: 1,\r\n           " +
                    "         render: function (data) {\r\n                        var links = [];\r\n   " +
                    "                     if (data != \"\") {\r\n                            links = data" +
                    ".split(\'|\');\r\n                            return \'<a href=\"\' + _spPageContextInf" +
                    "o.webAbsoluteUrl + \'/Lists/ManualTecnico/DispForm.aspx?ID=\' + links[1] + \'\" >\' +" +
                    " links[0] + \'</a><br/>\'\r\n                        }\r\n                    }\r\n     " +
                    "           },\r\n                {\r\n                    targets: 3,\r\n             " +
                    "       \"className\": \"tbCentro\"\r\n                },\r\n                {\r\n         " +
                    "           targets: 7,\r\n                    \"className\": \"tbCentro\",\r\n          " +
                    "          render: function (data) {\r\n                        var links = [];\r\n  " +
                    "                      if (data != \"\") \r\n                            links = data" +
                    ".split(\'|\');\r\n                        \r\n                        var link=\"\";\r\n  " +
                    "                      $.each(links, function (index, value) {\r\n                 " +
                    "           if (value != \"\") {\r\n                                if (value.include" +
                    "s(\'pdf\')) {\r\n                                    var im = value.split(\'#\');\r\n   " +
                    "                                 link += \'<a href=\"\' + _spPageContextInfo.webAbs" +
                    "oluteUrl + \'/SitePages/DocumentosMTC.aspx?Doc=\' + im[0] + \'&Link=\' + im[1] + \'\" " +
                    "target=\"_blank\">PDF</a><br/>\'\r\n                                }\r\n              " +
                    "                  else\r\n                                    link += \'<a href=\"\' " +
                    "+ value + \'\" >DOC</a><br/>\'\r\n                            }\r\n                    " +
                    "    });\r\n                        \r\n                        return link\r\n        " +
                    "            }\r\n                }\r\n            ]\r\n        });\r\n    });\r\n\r\n    fun" +
                    "ction ShowProgress() {\r\n        setTimeout(function () {\r\n            var modal " +
                    "= $(\'<div />\');\r\n            modal.addClass(\"modal\");\r\n            $(\'body\').app" +
                    "end(modal);\r\n            var loading = $(\".loading\");\r\n            loading.show(" +
                    ");\r\n            var top = Math.max($(window).height() / 2 - loading[0].offsetHei" +
                    "ght / 2, 0);\r\n            var left = Math.max($(window).width() / 2 - loading[0]" +
                    ".offsetWidth / 2, 0);\r\n            loading.css({ top: top, left: left });\r\n     " +
                    "   }, 200);\r\n    }\r\n\r\n    $(document).ready(function () {\r\n        $(\"#btPesquis" +
                    "ar\").click(function () {\r\n            ShowProgress();\r\n        });\r\n\r\n        $(" +
                    "\"#btLimpar\").click(function () {\r\n            ShowProgress();\r\n        });\r\n    " +
                    "});\r\n    </script>\r\n\r\n<div><h2 class=\"tituloPesquisa\">Pesquisar Manual Técnico d" +
                    "e Campo</h2></div>\r\n<div class=\"pesq\">\r\n    <div class=\"fields\">\r\n        <span " +
                    "class=\"labels\">Tipo </span>\r\n\r\n        ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Grupo </span" +
                    ">\r\n        ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Subgrupo </s" +
                    "pan>\r\n        ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Fabricante <" +
                    "/span>\r\n        ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Órgão Respos" +
                    "ável </span>\r\n        ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Inicio de Vi" +
                    "gência </span>\r\n        De ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("\r\n        &nbsp;até&nbsp;\r\n        ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n    ");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Fim de Vigência </span>\r" +
                    "\n        De ");
            parameterContainer.Controls[8].RenderControl(@__w);
            @__w.Write("\r\n        &nbsp;até&nbsp;\r\n        ");
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n    ");
            parameterContainer.Controls[10].RenderControl(@__w);
            @__w.Write("\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Controle de Status </spa" +
                    "n>\r\n        ");
            parameterContainer.Controls[11].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n    <div class=\"ui-widget fields\">\r\n        <span class=\"labels\">Pa" +
                    "lavra Chave </span>\r\n        ");
            parameterContainer.Controls[12].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Digite sua b" +
                    "usca </span>\r\n        ");
            parameterContainer.Controls[13].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n    <div style=\"margin-top:5px;padding-left:200px\">\r\n        ");
            parameterContainer.Controls[14].RenderControl(@__w);
            @__w.Write("\r\n        &nbsp;&nbsp;\r\n        ");
            parameterContainer.Controls[15].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n</div>\r\n<div style=\"margin-top:10px\">\r\n    ");
            parameterContainer.Controls[16].RenderControl(@__w);
            @__w.Write("\r\n    ");
            parameterContainer.Controls[17].RenderControl(@__w);
            @__w.Write("\r\n</div>\r\n");
            parameterContainer.Controls[18].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n<div class=\"loading\">\r\n    <br />Carregando, por favor aguarde...<br /><br " +
                    "/>\r\n    <img src=\"../SiteAssets/CSS/ajax-loader.gif\" alt=\"\" />\r\n</div>");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
