//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnas.OGX2.Chamados.WebPartPaginas.WP_PesquisaChamado {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class WP_PesquisaChamado {
        
        protected global::System.Web.UI.WebControls.TextBox txtNumChamado;
        
        protected global::System.Web.UI.WebControls.DropDownList drpStatus;
        
        protected global::System.Web.UI.WebControls.DropDownList drpTipoChamado;
        
        protected global::System.Web.UI.WebControls.TextBox dtIncio;
        
        protected global::System.Web.UI.WebControls.TextBox dtFim;
        
        protected global::System.Web.UI.WebControls.Label ErroDtInicio;
        
        protected global::System.Web.UI.WebControls.Label ErroDtFim;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ErrosDT;
        
        protected global::System.Web.UI.WebControls.TextBox txtBusca;
        
        protected global::System.Web.UI.WebControls.DropDownList drpGerencia;
        
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker solicitante;
        
        protected global::System.Web.UI.WebControls.DropDownList drpImportancia;
        
        protected global::System.Web.UI.WebControls.DropDownList drpComplexidade;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl onlyAdmin;
        
        protected global::System.Web.UI.WebControls.Button btPesquisar;
        
        protected global::System.Web.UI.WebControls.Button btLimpar;
        
        protected global::System.Web.UI.WebControls.GridView grid;
        
        protected global::System.Web.UI.WebControls.Label lblresultadoVazio;
        
        public static implicit operator global::System.Web.UI.TemplateControl(WP_PesquisaChamado target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtNumChamado() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtNumChamado = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtNumChamado";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Status --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control4() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Aberto";
            @__ctrl.Text = "Aberto";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control5() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Em andamento";
            @__ctrl.Text = "Em andamento";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control6() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Aguardando informações";
            @__ctrl.Text = "Aguardando informações";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control7() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Encaminhado à outra gerência da DO";
            @__ctrl.Text = "Encaminhado à outra gerência da DO";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control8() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Encerrado";
            @__ctrl.Text = "Encerrado";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control4();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control5();
            @__ctrl.Add(@__ctrl3);
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control6();
            @__ctrl.Add(@__ctrl4);
            global::System.Web.UI.WebControls.ListItem @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control7();
            @__ctrl.Add(@__ctrl5);
            global::System.Web.UI.WebControls.ListItem @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control8();
            @__ctrl.Add(@__ctrl6);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpStatus() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpStatus = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpStatus";
            this.@__BuildControl__control2(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control10() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione uma Tipo de Chamado --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control9(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control10();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpTipoChamado() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpTipoChamado = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpTipoChamado";
            this.@__BuildControl__control9(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControldtIncio() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.dtIncio = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dtIncio";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Date;
            @__ctrl.MaxLength = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControldtFim() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.dtFim = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dtFim";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Date;
            @__ctrl.MaxLength = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlErroDtInicio() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.ErroDtInicio = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ErroDtInicio";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Text = "As datas De - até de Data de Solicitação devem ser preenchidas.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlErroDtFim() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.ErroDtFim = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ErroDtFim";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Text = "A data final de Data de Solicitação deve ser maior que a data inicial.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlErrosDT() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.ErrosDT = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fields");
            @__ctrl.ID = "ErrosDT";
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <span class=\"labels\">&nbsp;&nbsp;</span>\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControlErroDtInicio();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControlErroDtFim();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtBusca() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtBusca = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtBusca";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control12() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione uma Gerência --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control11(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control12();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpGerencia() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpGerencia = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpGerencia";
            this.@__BuildControl__control11(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__BuildControlsolicitante() {
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ClientPeoplePicker();
            this.solicitante = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "solicitante";
            @__ctrl.ValidationEnabled = true;
            @__ctrl.AllowMultipleEntities = false;
            @__ctrl.PrincipalAccountType = "User";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(389D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control14() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Importância --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control15() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Aberto";
            @__ctrl.Text = "Baixa";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control16() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Média";
            @__ctrl.Text = "Média";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control17() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Alta";
            @__ctrl.Text = "Alta";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control13(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control14();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control15();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control16();
            @__ctrl.Add(@__ctrl3);
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control17();
            @__ctrl.Add(@__ctrl4);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpImportancia() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpImportancia = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpImportancia";
            this.@__BuildControl__control13(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control19() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "-- Selecione um Complexidade --";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control20() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Aberto";
            @__ctrl.Text = "Baixa";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control21() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Média";
            @__ctrl.Text = "Média";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control22() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "Alta";
            @__ctrl.Text = "Alta";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control18(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control19();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control20();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control21();
            @__ctrl.Add(@__ctrl3);
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control22();
            @__ctrl.Add(@__ctrl4);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpComplexidade() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.drpComplexidade = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "drpComplexidade";
            this.@__BuildControl__control18(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlonlyAdmin() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.onlyAdmin = @__ctrl;
            @__ctrl.ID = "onlyAdmin";
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <div class=\"fields\">\r\n            <span class=\"labels\">Encaminhado para" +
                        " </span>\r\n            "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControldrpGerencia();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n        <div class=\"fields\">\r\n            <span class=\"labels\" " +
                        "style=\"float:left;min-height:31px;\">Solicitante </span>\r\n            <div style=" +
                        "\"float:left;width: 700px;padding-bottom:6px;min-height:31px;\">\r\n                " +
                        ""));
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl2;
            @__ctrl2 = this.@__BuildControlsolicitante();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </div>\r\n        </div>\r\n        \r\n        <div class=\"fields\">\r\n   " +
                        "         <span class=\"labels\">Importância </span>\r\n            "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            @__ctrl3 = this.@__BuildControldrpImportancia();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n        <div class=\"fields\">\r\n            <span class=\"labels\">" +
                        "Complexidade </span>\r\n            "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl4;
            @__ctrl4 = this.@__BuildControldrpComplexidade();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtPesquisar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btPesquisar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btPesquisar";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Text = "Buscar";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(150D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.CssClass = "btDireita";
            @__ctrl.Click -= new System.EventHandler(this.btPesquisar_Click);
            @__ctrl.Click += new System.EventHandler(this.btPesquisar_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtLimpar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btLimpar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btLimpar";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Text = "Limpar Pesquisa";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(150D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.CssClass = "btEsquerda";
            @__ctrl.Click -= new System.EventHandler(this.btLimpar_Click);
            @__ctrl.Click += new System.EventHandler(this.btLimpar_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrid() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grid = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grid";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.CssClass = "cell-border stripe hover";
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblresultadoVazio() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblresultadoVazio = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblresultadoVazio";
            @__ctrl.Text = "Nenhum Chamado encontrado.";
            @__ctrl.Visible = false;
            @__ctrl.CssClass = "resultVazio";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Furnas.OGX2.Chamados.WebPartPaginas.WP_PesquisaChamado.WP_PesquisaChamado @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<style>\r\n    .modal{\r\n        position: fixed;\r\n        top: 0;\r\n        left" +
                        ": 0;\r\n        background-color: black;\r\n        z-index: 99;\r\n        opacity: 0" +
                        ".3;\r\n        filter: alpha(opacity=30);\r\n        -moz-opacity: 0.3;\r\n        min" +
                        "-height: 100%;\r\n        width: 100%;\r\n    }\r\n\r\n    .loading{\r\n        text-align" +
                        ": center;\r\n        font-family: Arial;\r\n        font-size: 10pt;\r\n        border" +
                        ": 2px solid #67CFF5;\r\n        width: 200px;\r\n        height: 110px;\r\n        dis" +
                        "play: none;\r\n        position: fixed;\r\n        background-color: White;\r\n       " +
                        " z-index: 999;\r\n        font-weight:bold;\r\n    }\r\n    .ms-webpartPage-root {\r\n  " +
                        "      border-spacing: 0px!important;\r\n        margin-top: 20px!important;\r\n    }" +
                        "\r\n    .custom-combobox {\r\n    position: relative;\r\n    display: inline-block;\r\n " +
                        " }\r\n  .custom-combobox-toggle {\r\n    position: absolute;\r\n    top: 0;\r\n    botto" +
                        "m: 0;\r\n    margin-left: -1px;\r\n    padding: 0;\r\n  }\r\n  .custom-combobox-input {\r" +
                        "\n    margin: 0;\r\n    padding: 5px 10px;\r\n  }\r\n  span#DeltaPlaceHolderPageTitleIn" +
                        "TitleArea {\r\n    display: none;\r\n}\r\n.labels {\r\n    width:230px;\r\n    float:left;" +
                        "\r\n}\r\n.pesq {\r\n    background-color: #f1f1f1;\r\n    padding:10px;\r\n    font-family" +
                        ": \"Segoe UI Light\",\"Segoe UI\",\"Segoe\",Tahoma,Helvetica,Arial,sans-serif;\r\n    co" +
                        "lor: #262626;\r\n    font-size:14px;\r\n    border-radius: 10px;\r\n    border: 1px so" +
                        "lid #ababab;\r\n}\r\n.tituloPesquisa {\r\n    font-family: \"Segoe UI Light\",\"Segoe UI\"" +
                        ",\"Segoe\",Tahoma,Helvetica,Arial,sans-serif;\r\n    font-size: 25px;\r\n    margin-bo" +
                        "ttom: 10px;\r\n    font-weight:bold;\r\n}\r\n.fields {\r\n    padding-bottom:8px;\r\n}\r\n.b" +
                        "tDireita {\r\n    margin-left: 0px!important;\r\n    background: url(../SiteAssets/m" +
                        "agnifier.png) left 40px top 8px no-repeat;\r\n    cursor: pointer;\r\n    border-rad" +
                        "ius: 5px;\r\n    font-size: 13px!important;\r\n    border: 1px solid #666!important;" +
                        "\r\n    padding-left: 25px!important;\r\n}\r\n.btEsquerda {\r\n    margin-left: 0px!impo" +
                        "rtant;\r\n    background: url(../SiteAssets/cross.png) left 20px top 9px no-repeat" +
                        ";\r\n    cursor: pointer;\r\n    font-size: 13px!important;\r\n    text-align: right;\r" +
                        "\n    padding-right: 15px!important;\r\n    border-radius: 5px;\r\n    border: 1px so" +
                        "lid #666!important;\r\n}\r\n.btExport {\r\n    margin-left: 0px!important;\r\n    backgr" +
                        "ound: url(../SiteAssets/excel.png) left 20px top 9px no-repeat;\r\n    cursor: poi" +
                        "nter;\r\n    font-size: 13px!important;\r\n    text-align: right;\r\n    padding-right" +
                        ": 15px!important;\r\n    border-radius: 5px;\r\n    border: 1px solid #666!important" +
                        ";\r\n}\r\n.resultVazio {\r\n    font-size:17px; \r\n    color:#262626;\r\n    font-family:" +
                        " \"Segoe UI Light\",\"Segoe UI\",\"Segoe\",Tahoma,Helvetica,Arial,sans-serif;\r\n    fon" +
                        "t-weight:bold;\r\n}\r\n.tbCentro {\r\n    text-align: center;\r\n}\r\nselect {\r\n    min-wi" +
                        "dth: 415px;\r\n}\r\n</style>\r\n\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../Site" +
                        "Assets/JSManual/jquery-ui.theme.min.css\" />\r\n<link rel=\"stylesheet\" type=\"text/c" +
                        "ss\" href=\"../SiteAssets/JSManual/jquery-ui.theme.css\" />\r\n<link rel=\"stylesheet\"" +
                        " type=\"text/css\" href=\"../SiteAssets/JSManual/jquery-ui.structure.min.css\" />\r\n<" +
                        "link rel=\"stylesheet\" type=\"text/css\" href=\"../SiteAssets/JSManual/jquery-ui.str" +
                        "ucture.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../SiteAssets/JSMan" +
                        "ual/jquery-ui.min.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../SiteA" +
                        "ssets/JSManual/jquery-ui.css\" />\r\n\r\n\r\n\r\n<link rel=\"stylesheet\" type=\"text/css\" h" +
                        "ref=\"../SiteAssets/JSManual/jquery.dataTables.min.css\" />\r\n<script type=\"text/ja" +
                        "vascript\" src=\"https://cdn.datatables.net/v/dt/dt-1.10.22/datatables.min.js\"></s" +
                        "cript>\r\n\r\n<script type=\"text/javascript\" src=\"../SiteAssets/JSChamados/tabelaCha" +
                        "mados.js\"></script>\r\n<script>\r\n\r\n\r\n    function ShowProgress() {\r\n        setTim" +
                        "eout(function () {\r\n            var modal = $(\'<div />\');\r\n            modal.add" +
                        "Class(\"modal\");\r\n            $(\'body\').append(modal);\r\n            var loading =" +
                        " $(\".loading\");\r\n            loading.show();\r\n            var top = Math.max($(w" +
                        "indow).height() / 2 - loading[0].offsetHeight / 2, 0);\r\n            var left = M" +
                        "ath.max($(window).width() / 2 - loading[0].offsetWidth / 2, 0);\r\n            loa" +
                        "ding.css({ top: top, left: left });\r\n        }, 200);\r\n    }\r\n\r\n    $(document)." +
                        "ready(function () {\r\n        $(\"#btPesquisar\").click(function () {\r\n            " +
                        "ShowProgress();\r\n        });\r\n\r\n        $(\"#btLimpar\").click(function () {\r\n    " +
                        "        ShowProgress();\r\n        });\r\n    });\r\n</script>\r\n\r\n<div><h2 class=\"titu" +
                        "loPesquisa\">Pesquisar Chamado</h2></div>\r\n<div class=\"pesq\">\r\n    <div class=\"fi" +
                        "elds\">\r\n        <span class=\"labels\">Número do Chamado </span>\r\n        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtNumChamado();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Status </spa" +
                        "n>\r\n        "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            @__ctrl2 = this.@__BuildControldrpStatus();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Tipo de Cham" +
                        "ado </span>\r\n        "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            @__ctrl3 = this.@__BuildControldrpTipoChamado();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Data de Soli" +
                        "citação </span>\r\n        De "));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControldtIncio();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        &nbsp;até&nbsp;\r\n        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            @__ctrl5 = this.@__BuildControldtFim();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl6;
            @__ctrl6 = this.@__BuildControlErrosDT();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <div class=\"fields\">\r\n        <span class=\"labels\">Digite sua Busca </span>" +
                        "\r\n        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            @__ctrl7 = this.@__BuildControltxtBusca();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl8;
            @__ctrl8 = this.@__BuildControlonlyAdmin();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <div style=\"margin-top:5px;padding-left:230px\">\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl9;
            @__ctrl9 = this.@__BuildControlbtPesquisar();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        &nbsp;&nbsp;\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl10;
            @__ctrl10 = this.@__BuildControlbtLimpar();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n</div>\r\n<div style=\"margin-top:10px\">\r\n    "));
            global::System.Web.UI.WebControls.GridView @__ctrl11;
            @__ctrl11 = this.@__BuildControlgrid();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            global::System.Web.UI.WebControls.Label @__ctrl12;
            @__ctrl12 = this.@__BuildControllblresultadoVazio();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</div>\r\n\r\n<div class=\"loading\">\r\n    <br />Carregando, por favor aguarde...<br " +
                        "/><br />\r\n    <img src=\"../SiteAssets/CSS/ajax-loader.gif\" alt=\"\" />\r\n</div>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
