//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnas.OGX2.MTC.WebPartsPaginas.WP_ValidaUsuariosMTC {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class WP_ValidaUsuariosMTC {
        
        protected global::System.Web.UI.WebControls.HiddenField ocultoResp;
        
        public static implicit operator global::System.Web.UI.TemplateControl(WP_ValidaUsuariosMTC target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlocultoResp() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.ocultoResp = @__ctrl;
            @__ctrl.ID = "ocultoResp";
            @__ctrl.Value = "TRUE";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Furnas.OGX2.MTC.WebPartsPaginas.WP_ValidaUsuariosMTC.WP_ValidaUsuariosMTC @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"


<style type=""text/css"">  
/*hr[class=""ms-core-menu-separatorHr""]{display:none;}*/
li[text=""Baixar uma cópia""]
{  display:none;}  
li[text=""Fazer Check-in""]
{  display:none;}  
li[text=""Descartar Check-out""]
{  display:none;}
/*li[text=""Histórico de Versões""]
{  display:none;}*/
li[text=""Detalhes da Conformidade""]
{  display:none;}
li[text=""Fluxos de Trabalho""]
{  display:none;}
/*li[text=""Compartilhado com""]
{  display:none;}*/
</style>

<style type=""text/css"">

li[id$='Ribbon.List.TagsAndNotes'] {
display:none;
}
li[id$='Ribbon.List.Actions'] {
display:none;
}
 li[id$='Ribbon.ListItem.Actions'] {
display:none;
}
 li[id$='Ribbon.List.Share'] {
display:none;
}
 li[id$='Ribbon.List.CustomizeList'] {
display:none;
}
 li[id$='Ribbon.Documents.Workflow'] {
display:none;
}
li[id$='Ribbon.ListItem.TagsAndNotes'] {
display:none;
}
li[id$='Ribbon.ListItem.Share'] {
display:none;
}
li[id$='Ribbon.ListItem.Workflow'] {
display:none;
}
</style>

"));
            global::System.Web.UI.WebControls.HiddenField @__ctrl1;
            @__ctrl1 = this.@__BuildControlocultoResp();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<script>
    function Esconde() {
        if ($(""input[id*='ocultoResp']"").val() == 'FALSE') {
            $('#Hero-WPQ2').remove();
        }
        else if ($(""input[id*='ocultoResp']"").val() == 'ADMIN') {
            var url = _spPageContextInfo.webAbsoluteUrl + ""/SitePages/NovoMTC.aspx"";
            $(""#idHomePageNewItem"").attr(""onclick"", ""OpenDialog('"" + url + ""','Manual Técnico de Campo');return false;"");
        }
    }

    function OpenDialog(url, title) {
        var options = {
            url: url,
            width: 300,
            height: 250,
            title: title,
            dialogReturnValueCallback: Function.createDelegate(null, CloseDialogCallback)
        };
        SP.SOD.execute('sp.ui.dialog.js', 'SP.UI.ModalDialog.showModalDialog', options);
    }
</script>

<!--<script type=""text/javascript"">
function EscondeUpload(){
    $(""#Hero-WPQ2"").remove();
}
</script>
<script type=""text/javascript"">
            AddSendSubMenu = function (m, ctx) { }
            _spBodyOnLoadFunctionNames.push(""resetAddSendSubMenu()"");
            function resetAddSendSubMenu() {
                AddSendSubMenu = function (m, ctx) { };
            }
</script>-->"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
